repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.8.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-rust
    entry: rustfmt --edition 2018
    files: ^.*\.rs$
- repo: local
  hooks:
  - id: rust-clippy
    name: Rust clippy
    description: Run cargo clippy on files included in the commit. clippy must be installed before-hand.
    entry: cargo clippy -- -D warnings
    pass_filenames: false
    types: [file, rust]
    language: system
